version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: demo-uppy-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./demo_uploader.db
      - SECRET_KEY=your-secret-key-change-in-production
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./data:/app/data
      - backend_uploads:/app/uploads
    networks:
      - demo-uppy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demo-uppy-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - demo-uppy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_uploads:
    driver: local

networks:
  demo-uppy-network:
    driver: bridge
